# dev-hop-key.tf
#
# A dedicated SSH key for hopping BETWEEN dev servers.
#
# THE PROBLEM THIS SOLVES: fcvm-metal-arm was carrying ~/.ssh/fcvm-ec2 -- the private half
# of the key that logs in to the jumpbox. Nothing on the box used it (runner access goes
# through ~/.ssh/runner_key, per ~/.ssh/config), but anything able to read that file could
# SSH to the jumpbox, which is where the AWS admin session lives. That inverts the intended
# trust direction: phone -> jumpbox -> dev server, never dev server -> jumpbox. It matters
# more than usual here because the dev boxes run agents with --dangerously-skip-permissions.
#
# THE FIX: a separate keypair whose public half is authorized ONLY on dev servers, never on
# the jumpbox. Dev boxes can then reach each other, and holding this key gets you nothing
# but another dev box. The fcvm-ec2 private key is deleted from the dev servers.
#
# WHY A KEY AT ALL, rather than `ssh -A` agent forwarding: agent forwarding would leave no
# key material on disk and is strictly better -- but only when you arrive via the jumpbox.
# Connecting from the phone straight to a dev server, which is a supported path here, has
# no agent to forward, and hops would silently stop working.

resource "tls_private_key" "dev_hop" {
  algorithm = "ED25519"
}

resource "aws_secretsmanager_secret" "dev_hop" {
  name        = "dev-hop-ssh-key"
  description = "SSH key for dev-server-to-dev-server hops. Deliberately NOT authorized on the jumpbox."

  # Long enough to notice and restore a mistake, short enough that a rotation actually
  # takes effect rather than leaving the old key recoverable for a month.
  recovery_window_in_days = 7

  tags = { Name = "dev-hop-ssh-key", Managed = "terraform" }
}

resource "aws_secretsmanager_secret_version" "dev_hop" {
  secret_id = aws_secretsmanager_secret.dev_hop.id
  secret_string = jsonencode({
    private = tls_private_key.dev_hop.private_key_openssh
    public  = trimspace(tls_private_key.dev_hop.public_key_openssh)
  })
}

# ---------------------------------------------------------------------------------
# Installed for the `ubuntu` user only -- NOT for the kids' accounts on the Next.js box.
# colton and connor have no business reaching the Firecracker metal boxes, and /home/ubuntu
# is 0700 so they cannot read it there either.
# ---------------------------------------------------------------------------------
locals {
  dev_hop_setup = <<-HOP
# Fetch the shared dev-hop key and wire up host aliases.
HOPJSON=$(aws secretsmanager get-secret-value --secret-id dev-hop-ssh-key \
  --region us-west-1 --query SecretString --output text 2>/dev/null)

if [ -n "$HOPJSON" ]; then
  install -d -m 700 -o ubuntu -g ubuntu /home/ubuntu/.ssh

  printf '%s' "$HOPJSON" | python3 -c 'import sys,json;print(json.load(sys.stdin)["private"])' \
    > /home/ubuntu/.ssh/dev_hop
  printf '%s' "$HOPJSON" | python3 -c 'import sys,json;print(json.load(sys.stdin)["public"])' \
    > /home/ubuntu/.ssh/dev_hop.pub
  chmod 600 /home/ubuntu/.ssh/dev_hop
  chmod 644 /home/ubuntu/.ssh/dev_hop.pub
  chown ubuntu:ubuntu /home/ubuntu/.ssh/dev_hop /home/ubuntu/.ssh/dev_hop.pub

  # Authorize it for inbound hops. grep -qxF so re-running never appends a duplicate --
  # the runner_key block in ~/.ssh/config grew to three identical copies exactly this way.
  HOPPUB=$(cat /home/ubuntu/.ssh/dev_hop.pub)
  touch /home/ubuntu/.ssh/authorized_keys
  grep -qxF "$HOPPUB" /home/ubuntu/.ssh/authorized_keys 2>/dev/null || \
    echo "$HOPPUB" >> /home/ubuntu/.ssh/authorized_keys
  chmod 600 /home/ubuntu/.ssh/authorized_keys
  chown ubuntu:ubuntu /home/ubuntu/.ssh/authorized_keys

  # Host aliases, written to their own file and Included, so the block is replaceable
  # wholesale and can never accumulate duplicates in the main config.
  #
  # Addresses are resolved from EC2 at write time rather than hardcoded: these are spot
  # instances, so a reclaim mints a new private IP and a baked-in address would quietly
  # point at nothing. Regenerate any time with `devhop-refresh`.
  cat > /usr/local/bin/devhop-refresh <<'REFRESH'
#!/bin/bash
# Rewrite ~/.ssh/config.d-devhop from the current private IPs of the dev servers.
set -uo pipefail
OUT=/home/ubuntu/.ssh/config.d-devhop
TMP=$(mktemp)
printf '# generated by devhop-refresh -- do not edit, changes are overwritten\n\n' > "$TMP"
FOUND=0
for entry in "fcvm-arm:fcvm-metal-arm" "fcvm-x86:fcvm-metal-x86" "nextjs:nextjs-dev"; do
  alias_name="$${entry%%:*}"; tag="$${entry##*:}"
  ip=$(aws ec2 describe-instances --region us-west-1 \
        --filters "Name=tag:Name,Values=$tag" "Name=instance-state-name,Values=running" \
        --query 'Reservations[].Instances[0].PrivateIpAddress' --output text 2>/dev/null | head -1)
  case "$ip" in ''|None) continue ;; esac
  printf 'Host %s %s\n    HostName %s\n    User ubuntu\n    IdentityFile ~/.ssh/dev_hop\n    StrictHostKeyChecking accept-new\n\n' \
    "$alias_name" "$tag" "$ip" >> "$TMP"
  FOUND=$((FOUND+1))
done
# Never replace a good config with an empty one because the API call failed.
if [ "$FOUND" -gt 0 ]; then
  install -m 600 -o ubuntu -g ubuntu "$TMP" "$OUT"
  echo "devhop: wrote $FOUND host(s) to $OUT"
else
  echo "devhop: resolved no instances; keeping existing $OUT" >&2
fi
rm -f "$TMP"
REFRESH
  chmod 755 /usr/local/bin/devhop-refresh
  /usr/local/bin/devhop-refresh || true

  touch /home/ubuntu/.ssh/config
  grep -qxF "Include ~/.ssh/config.d-devhop" /home/ubuntu/.ssh/config 2>/dev/null || \
    sed -i '1i Include ~/.ssh/config.d-devhop' /home/ubuntu/.ssh/config
  chown ubuntu:ubuntu /home/ubuntu/.ssh/config
  chmod 600 /home/ubuntu/.ssh/config

  # The whole point: the jumpbox's key must not live on a dev server. Nothing here uses it
  # (verified: ~/.ssh/config routes runners through runner_key, and the only reference to
  # fcvm-ec2 on the box was the PUBLIC half in authorized_keys, for inbound login).
  if [ -f /home/ubuntu/.ssh/fcvm-ec2 ]; then
    shred -u /home/ubuntu/.ssh/fcvm-ec2 2>/dev/null || rm -f /home/ubuntu/.ssh/fcvm-ec2
    echo "removed jumpbox private key from this dev server"
  fi
  rm -f /home/ubuntu/.ssh/fcvm-ec2.pub
else
  echo "WARNING: could not read dev-hop-ssh-key; leaving ssh config alone"
fi
HOP
}

output "dev_hop_usage" {
  description = "How to hop between dev servers"
  value       = "from any dev server, as ubuntu: ssh fcvm-arm | ssh fcvm-x86 | ssh nextjs"
}
